Pocket/content-monorepo

servers/curated-corpus-api/schema-admin.graphql, servers/curated-corpus-api/src/admin/resolvers/mutations/ApprovedItem/index.ts, servers/curated-corpus-api/src/database/mutations/ApprovedItem.integration.ts, servers/curated-corpus-api/src/database/mutations/ApprovedItem.ts, servers/curated-corpus-api/src/database/mutations/SectionItem.integration.ts, servers/curated-corpus-api/src/database/mutations/SectionItem.ts
delete associated SectionItems when deleting the parent ApprovedItem. this is required for DB referential integrity, as a SectionItem is just a pointer to an ApprovedItem
- i know the test here is really just testing that Prisma does what we expect, but it feels like a good sanity check, particularly given that the operation is destructive.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/MC-1643
=> feat: delete associated SectionItems when deleting the parent ApprovedItem

.github/workflows/section-manager-lambda.yml, lambdas/corpus-scheduler-lambda/src/types.ts, lambdas/section-manager-lambda/package.json, lambdas/section-manager-lambda/src/graphQlApiCalls.ts, lambdas/section-manager-lambda/src/index.integration.ts, lambdas/section-manager-lambda/src/index.spec.ts, lambdas/section-manager-lambda/src/index.ts, lambdas/section-manager-lambda/src/types.ts, lambdas/section-manager-lambda/src/utils.spec.ts, lambdas/section-manager-lambda/src/utils.ts, lambdas/section-manager-lambda/src/validators.spec.ts
section manager lambda - create section items
- move index integration tests to spec tests (all external calls are mocked)
- remove integration test job from CI (no .integration.ts files exist)
pushed to dev and sent a test payload through SQS - all worked as expected! we'll be testing this further in dev with real ML payloads before going live.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/MC-1645
=> feat: section manager lambda - create section items

packages/content-common/src/types.ts, servers/curated-corpus-api/schema-admin.graphql, servers/curated-corpus-api/src/config/index.ts
Adding "Sections" to `ActionScreen` enum for indicating where an action took place from in the admin tool.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/MC-1671
=> MC-1671: adding Sections to ActionScreen enum

lambdas/corpus-scheduler-lambda/src/types.ts, lambdas/corpus-scheduler-lambda/src/utils.spec.ts, lambdas/corpus-scheduler-lambda/src/validation.spec.ts, lambdas/section-manager-lambda/src/types.ts, lambdas/section-manager-lambda/src/utils.spec.ts, lambdas/section-manager-lambda/src/validators.spec.ts
refactor type validation in corpus scheduler and section manager lambdas
- for optional fields, ML is sending `null`. our types expected `undefined`. this commit updates types for optional fields to accept `{type}` or `null`
- ML has confirmed that all optional fields will always be sent with each payload, with a value of `null` if the field value cannot be derived.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/MC-1675
=> refactor: type validation in corpus scheduler and section manager lambdas

lambdas/prospect-translation-lambda/src/lib.spec.ts, lambdas/prospect-translation-lambda/src/lib.ts
fix bug when hydrating prospect with language without title or excerpt. addresses [this](https://pocket.sentry.io/issues/6358932511/?alert_rule_id=15181376&alert_type=issue&environment=production&notification_uuid=26a6f6ae-a36d-4d21-99aa-fe62f8bd4056&project=4507222652813312&referrer=slack) sentry error.
=> fix: fix bug when hydrating prospect with language without title or excerpt

servers/curated-corpus-api/prisma/migrations/20250305203859_add_disabled_to_section/migration.sql, servers/curated-corpus-api/prisma/schema.prisma
We want curators to be able to disable/enable individual sections via the admin tool. Only enabled sections will be fed to Merino -> New Tab.
Adding new `disabled` `boolean` field to the Prisma `Section` DB model. 
- `false` by default
- can only be set via the admin tools.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/MC-1677
=> MC-1677: adding disabled boolean field to Section DB model

packages/content-common/src/types.ts, servers/curated-corpus-api/schema-admin.graphql, servers/curated-corpus-api/src/admin/resolvers/index.ts, servers/curated-corpus-api/src/admin/resolvers/mutations/Section/disableEnableSection.integration.ts, servers/curated-corpus-api/src/admin/resolvers/mutations/Section/index.ts, servers/curated-corpus-api/src/admin/resolvers/mutations/sample-mutations.gql.ts, servers/curated-corpus-api/src/database/mutations/Section.integration.ts, servers/curated-corpus-api/src/database/mutations/Section.ts, servers/curated-corpus-api/src/database/mutations/index.ts, servers/curated-corpus-api/src/database/types.ts
Adding a dedicated admin api mutation `disableEnableSection` to disable or enable sections. This mutation is to be only used via the admin tool.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/MC-1679
=> MC-1679: adding disable & enable Section mutation

packages/content-common/src/index.spec.ts, packages/content-common/src/index.ts
[MC-1682](https://mozilla-hub.atlassian.net/browse/MC-1682) Fix capitalization after an apostrophe [reported by editorial](https://mozilla.slack.com/archives/C05EVRU1U1X/p1741826855322319):
[MC-1682]: https://mozilla-hub.atlassian.net/browse/MC-1682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MC-1682] fix: capitalization after curly apostrophe

servers/curated-corpus-api/src/admin/resolvers/mutations/ApprovedItem/auth.integration.ts, servers/curated-corpus-api/src/admin/resolvers/mutations/ApprovedItem/index.ts, servers/curated-corpus-api/src/admin/resolvers/mutations/ApprovedItem/rejectApprovedCorpusItemsForDomain.integration.ts, servers/curated-corpus-api/src/admin/resolvers/types.ts, servers/curated-corpus-api/src/admin/routes/admin.ts, servers/curated-corpus-api/src/database/queries/ApprovedItem.ts, servers/curated-corpus-api/src/database/queries/ScheduledItem.ts, servers/curated-corpus-api/src/database/queries/index.ts, servers/curated-corpus-api/src/express.ts
There has been a request to delete several approved corpus items and all related scheduled items for a domain.
Added a POST REST endpoint to the admin curated corpus api: `/admin/reject-approved-corpus-items-for-domain`:
* takes in two params: `domainName` & `testing`
* if `testing`=`false`, approved items for the domain are rejected/unscheduled
* if `testing`=`true`, the count of approved items found for the domain is returned
* Example request body:
```
{
"domainName": "elpais.com",
"testing": false
} 
```
* Added the new REST endpoint in `admin/routes`
* Created a new function/mutation `rejectApprovedCorpusItemsForDomain` which takes in a `domainName` &:
* finds all approved items for the domain
* finds all scheduled items for the approved item
* unschedules each item
* rejects the …
=> MC-1698: adding REST endpoint to admin corpus api for rejecting & unscheduling approved items for a domain

servers/curated-corpus-api/src/admin/resolvers/mutations/ApprovedItem/auth.integration.ts, servers/curated-corpus-api/src/admin/resolvers/mutations/ApprovedItem/rejectApprovedCorpusItemsForDomain.integration.ts, servers/curated-corpus-api/src/express.ts
Removing the corpus API REST endpoint `/admin/reject-approved-corpus-items-for-domain`.
Keeping the code but unmounting from the admin server. Skipping tests covering this endpoint.
Endpoint can be un-commented and re-deployed in the future if there is a use-case.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/MC-1699
=> MC-1699: remove REST endpoint /admin/reject-approved-corpus-items-for-domain

servers/curated-corpus-api/prisma/migrations/20250408194933_add_deactivate_reasons_to_section_item/migration.sql, servers/curated-corpus-api/prisma/schema.prisma
Adding new optional field `deactivateReasons` on `SectionItem`. Stored as `JSON` as for MySQL, Prisma does not support native array fields `String[]`. The client will send an array of string reasons to the graph, and will be stored as `JSON`.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/HNT-499
=> HNT-499: Updating Prisma schema - Adding deactivateReasons on SectionItem

packages/content-common/src/types.ts, servers/curated-corpus-api/schema-admin.graphql, servers/curated-corpus-api/src/admin/resolvers/mutations/SectionItem/index.ts, servers/curated-corpus-api/src/admin/resolvers/mutations/SectionItem/removeSectionItem.integration.ts, servers/curated-corpus-api/src/admin/resolvers/mutations/sample-mutations.gql.ts, servers/curated-corpus-api/src/database/mutations/SectionItem.integration.ts, servers/curated-corpus-api/src/database/mutations/SectionItem.ts, servers/curated-corpus-api/src/database/types.ts
Updating `removeSectionItem` mutation to set & store new field `deactivateReasons`.
- Added new enum `SectionItemRemovalReason` enum in the graph, will be used in the admin tool
- Updated Graphql mutation `removeSectionItem` to take in `RemoveSectionItemInput`.
- takes in `externalID` & array of `SectionItemRemovalReason` enum vals
- Updated resolver & db `removeSectionItem` to set & store `deactivateReasons`.
- Updated integration tests to check for the new `deactivateReasons`.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/HNT-500
=> (feat) HNT-500: update removeSectionItem mutation to store deactivateReasons

servers/curated-corpus-api/src/admin/resolvers/iabCategories.ts
Generated the [IAB taxonomy v3.0](https://github.com/InteractiveAdvertisingBureau/Taxonomies/blob/main/Content%20Taxonomies/Content%20Taxonomy%203.0.tsv) locally & adding generated dictionary to the Corpus API.
- generated file size ~ 90 KB
- 703 categories total
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/HNT-577
=> HNT-577: adding IAB taxonomy dict v3.0

servers/curated-corpus-api/prisma/migrations/20250428235231_add_iab_to_section/migration.sql, servers/curated-corpus-api/prisma/schema.prisma
Adding new optional field `iab` on `Section`. This will store the IAB taxonomy version & IAB category code(s) as a `json`:
```
{
"taxonomy": "IAB-3.0",
"categories": ["WQC6HR"]
}
```
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/HNT-578
=> HNT-578: adding iab JSON on Section prisma

lambdas/section-manager-lambda/src/testHelpers.ts, lambdas/section-manager-lambda/src/types.ts, lambdas/section-manager-lambda/src/utils.spec.ts, lambdas/section-manager-lambda/src/utils.ts, lambdas/section-manager-lambda/src/validators.spec.ts
Section-Manager Lambda update: Adding an optional `iab` metadata to `SqsSectionWithSectionItems`.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/HNT-580
=> HNT-580: section-manager-lambda - handle IAB metadata

lambdas/corpus-scheduler-lambda/package.json, lambdas/section-manager-lambda/package.json, pnpm-lock.yaml, servers/collection-api/nodemon.json, servers/collection-api/src/express.spec.ts, servers/collection-api/src/express.ts, servers/curated-corpus-api/nodemon.json, servers/curated-corpus-api/src/express.spec.ts, servers/curated-corpus-api/src/express.ts, servers/prospect-api/src/express.spec.ts, servers/prospect-api/src/express.ts
- Add missing DATABASE_URL environment variable for collection-api
- Resolve failed Prisma migration 20210716114553_add_collection_partnerships
- Install nodemon as workspace dependency and in lambda packages
- Fix nodemon infinite restart loops by configuring proper watch/ignore patterns
- Update watch scripts to use 'npx nodemon --watch src --ignore dist'
Fixed multiple startup failures preventing local development environment from running. All services now start successfully allowing developers to work locally.
=> HNT-758-fix-apollo-graphql-local-dev

servers/curated-corpus-api/prisma/migrations/20250729235557_add_custom_section_metadata_to_section/migration.sql, servers/curated-corpus-api/prisma/schema.prisma
Add custom section metadata to the `Section` prisma schema. All new metadata is optional.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/HNT-874
=> HNT-874: Add custom section metadata to Section prisma schema

.github/workflows/pull-request.yml
This PR introduces a no‑op `test-integrations` job to the Pull Request workflow. Its purpose is to ensure that a test‑integrations status check is always present on every PR, allowing branch protection rules to reliably require it without depending on path filters or other jobs. Without this no-op job, PRs that don't run any integration tests (such as documentation changes) would not be permitted to be merged in.
[Slack thread](https://mozilla.slack.com/archives/C08JXUR7J5S/p1753905253611949?thread_ts=1753902935.518699&cid=C08JXUR7J5S)
=> Allow test-integrations to be required before merging

servers/curated-corpus-api/prisma/migrations/20250730235022_remove_custom_section_metadata/migration.sql, servers/curated-corpus-api/prisma/schema.prisma
This PR reverts commit b6d34b1db7fb2492850d908af661a9a969eb524b.
-
-
JIRA ticket:
- Link to JIRA ticket
Issue:
- Link to GitHub issue
Documentation:
- Project doc
=> removing custom section metadata from Section prisma schema

servers/curated-corpus-api/prisma/migrations/20250731000630_add_custom_section_metadata_to_section/migration.sql, servers/curated-corpus-api/prisma/schema.prisma
Add custom section metadata to the `Section` prisma schema. All new metadata is optional.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/HNT-874
=> HNT-874: update Section DB to add custom metadata

.gitignore, servers/curated-corpus-api/schema-admin.graphql, servers/curated-corpus-api/schema-shared.graphql
What changed? What is the business/product goal?
- Added custom metadata fields to GraphQL Section type to support editorial
sections with enhanced content capabilities
- Introduced section lifecycle management through status tracking and date-based
scheduling to enable better control over section visibility and timing
Implementation Decisions
- Made all new fields optional to maintain backward compatibility with existing
sections
- Placed SectionStatus enum in admin schema only, as status management is an
administrative function
- Used Date scalar for date fields to align with existing date field patterns in
the schema (e.g., scheduledDate)
- Added editorial fields (description, heroTitle, heroDescription) to shared
schema for client consumption
Deployment steps
- Database migrations? …
=> HNT-875-feat: add custom section metadata fields to GraphQL schemas

servers/curated-corpus-api/src/shared/resolvers/fields/SectionStatus.spec.ts, servers/curated-corpus-api/src/shared/resolvers/fields/SectionStatus.ts, servers/curated-corpus-api/src/shared/utils.spec.ts, servers/curated-corpus-api/src/shared/utils.ts
Sections scheduled with a `startDate` one day after the `currentDate` were incorrectly evaluated as `LIVE` instead of `SCHEDULED`  — but only in certain timezones (e.g. America/New_York).
This happened because we were using `DateTime.fromJSDate()` to convert `Date` objects to Luxon `DateTime`, which treats the original date as midnight in UTC, not in the intended local timezone. As a result, a Date like **2024-06-16** was interpreted as **2024-06-15T20:00:00-04:00** in New York — shifting the effective date back by one day.
Convert `startDate` and `endDate` using `DateTime.fromObject()` instead of `fromJSDate()`. This ensures we always interpret the UI-selected date as a local calendar day.
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/HNT-1114
=> HNT-1114: fix section status computation
